<?php
gen = new Array([
 'Loading...',
 'Mii Transferring Avatar and Other in Your Mii Body',
 'Analyzing data...',
 'Creating save data...',
 'Saving days and data when you left Wii Console...',
 'Shake Wiimote to play your fish',
 'Connecting the internet...',
 'Wiimote Battery 2 Cube Left: You need Yoko-Chan Battery Up Line and battery up again',
 'Cube Battery life Has been 10 cube(28000 block of pin)',
 'Fish hungry',
 'Fish angry',
 'World Time has been paused due to server has been error',
 'World Time has been resuming running, World Time Country: Asia',
 'Data Save transferred by Wii Transfer App, Are you create again?',
 'Creating save data again...',
 'Please insert disc Wii NeYu to Your Console',
 'Verifing disc...',
 'Please enable Wii Fish Balance',
 'Start up on, Please do not power off and fish to Wii Fish Balance',
 'Please shake the Wiimote to fish to Wii Fish Balance',
 'Great, Step up and Please wait for Moment...',
 'Please enable Wii Step Balance',
 'Start up on, Please wait...',
 'Step up Wii Step Balance...',
 'Stepping down',
 'Great, Wii Fish Balance and Wii Step Balance has been enabled',
 'Select below in Wikmote[Left=<, Right=>, Up=^, Down]',
 'Verifing the game when Dante Start...',
 'You Win',
 'You lose',
 'Your Fish weight loss, Please shake give powder fish',
 'Your BMA has been changed, We sented Your BMA to Wii Fit Plus',
 'Verifing disc',
 'Disc Ejected',
 'You teleported main menu to you, Minigame are need disc Wii NeYu to play',
 'Saved the data..., You can view block saved from App Wii Savers',
 'Fish Plaza',
 'Exit game?',
 'Bye'
])
?>
